// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools 2015 v1.7.158
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FileDiffer
{
    static class Vsix
    {
        public const string Id = "ea5c68d6-cdae-4e79-bd46-2a39e95bb256";
        public const string Name = "File Differ";
        public const string Description = "The easiest way to diff two files directly in Solution Explorer";
        public const string Language = "en-US";
        public const string Version = "1.2";
        public const string Author = "Mads Kristensen";
        public const string Tags = "compare, files, diff";
    }
}
