// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FileDiffer
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPackageString = "6e490dec-1b23-471e-8120-f164af6b268a";
        public static Guid guidPackage = new Guid(guidPackageString);

        public const string guidDiffFilesCmdSetString = "5034b97c-760a-45e5-a15d-d86dcfae06f7";
        public static Guid guidDiffFilesCmdSet = new Guid(guidDiffFilesCmdSetString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int FilesMenuGroup = 0x1020;
        public const int GitMenuGroup = 0x1030;
        public const int FlyoutMenu = 0x1040;
        public const int DiffFilesCommandId = 0x0100;
        public const int Unmodified = 0x0110;
        public const int PreviousVersion = 0x0120;
        public const int Clipboard = 0x0130;
        public const int FileOnDisk = 0x0140;
    }
}
