// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FileDiffer
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPackageString = "6e490dec-1b23-471e-8120-f164af6b268a";
        public static Guid guidPackage = new Guid(guidPackageString);

        public const string guidDiffFilesCmdSetString = "5034b97c-760a-45e5-a15d-d86dcfae06f7";
        public static Guid guidDiffFilesCmdSet = new Guid(guidDiffFilesCmdSetString);

        public const string guidSolutionExplorerToolWindowString = "3ae79031-e1bc-11d0-8f78-00a0c9110057";
        public static Guid guidSolutionExplorerToolWindow = new Guid(guidSolutionExplorerToolWindowString);

        public const string GitPackageString = "57735d06-c920-4415-a2e0-7d6e6fbdfa99";
        public static Guid GitPackage = new Guid(GitPackageString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int FilesMenuGroup = 0x1020;
        public const int GitMenuGroup = 0x1030;
        public const int FlyoutMenu = 0x1040;
        public const int EditorFlyoutMenu = 0x1050;
        public const int EditorFlyoutMenuGroup = 0x1060;
        public const int DiffFilesCommandId = 0x0100;
        public const int Unmodified = 0x0110;
        public const int PreviousVersion = 0x0120;
        public const int Clipboard = 0x0130;
        public const int FileOnDisk = 0x0140;
        public const int EditorSelectionClipboard = 0x0150;
        public const int EditorBufferClipboard = 0x0160;
        public const int EditorBufferFile = 0x0170;
        public const int GitEditorContextGroup = 0xE002;
    }
}
